services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: suckato-backend
    restart: unless-stopped
    command: ["node", "/code/src/server.js"]
    ports:
      - 3000:3000
    networks:
      - suckato-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: suckato-frontend
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - suckato-net

networks:
  suckato-net:
    driver: bridge
